

export const PRODUCT_LOADING = "PRODUCT_LOADING"
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS"
export const PRODUCT_ERROR = "PRODUCT_ERROR"


export const GET_PRODUCT_LOADING = "GET_PRODUCT_LOADING"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR"
